name: Deploy to self-hosted runner

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to GHCR
        run: docker login ghcr.io -u "${{ github.repository_owner }}" -p ${{ secrets.GITHUB_TOKEN }}

      - name: Pull docker images
        run: docker compose -f docker-compose-dev.yml pull
        shell: cmd

      - name: Run docker compose up
        run: docker compose up -d
        shell: cmd
